import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import LogoutBtn from "./LogoutBtn";
import DarkMode from "./DarkMode";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // get Server Session information, authOptions required
  const session = await getServerSession(authOptions);

  const modeCookie = cookies().get("mode");

  console.log(modeCookie);

  return (
    <html lang="en">
      <body
        className={
          modeCookie != undefined && modeCookie.value === "dark"
            ? "dark-mode"
            : ""
        }
      >
        <div className="navbar">
          <Link href="/" className="logo">
            Tony forum
          </Link>
          <Link href="/list">List</Link>
          {session ? (
            <span>
              {session.user.name}
              <LogoutBtn />
            </span>
          ) : (
            <LoginBtn />
          )}
          <DarkMode />
        </div>
        {children}
      </body>
    </html>
  );
}
